name: CI

on:
  pull_request:
    paths:
      - '.github/**'
      - 'packages/**'
      - 'package.json'
  push:
    branches:
      - master

jobs:
  ci:
    name: Test on ${{ matrix.node_version }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node_version: ['10.x', '12.x', '14.x']
        os: [ubuntu-latest, macOS-latest, windows-latest]
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build:production

      - name: Test
        run: npm test
